students/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('studentscrud.urls')),
    path('admin/', admin.site.urls),
]

studentscrud/urls.py
from django.urls import path

from . import views

app_name = 'studentscrud'
urlpatterns = [
    path('', views.StudentsView.as_view(), name='estudiantes'),
    # Estudiantes
    path('estudiante/<int:pk>/', views.StudentView.as_view(), name='estudiante'),
    path('estudiante/nuevo/', views.EstudianteCreateView.as_view(), name='estudiante-nuevo'),
    path('estudiante/<int:pk>/editar', views.EstudianteUpdateView.as_view(), name='estudiante-editar'),
    path('estudiante/<int:pk>/borrar/', views.EstudianteDeleteView.as_view(), name='estudiante-borrar'),
    # Ciudades
    path('ciudades', views.CiudadesView.as_view(), name='ciudades'),
    path('ciudad/<int:pk>/', views.CiudadView.as_view(), name='ciudad'),
    path('ciudad/nuevo/', views.CiudadCreateView.as_view(), name='ciudad-nuevo'),
    path('ciudad/<int:pk>/editar', views.CiudadUpdateView.as_view(), name='ciudad-editar'),
    path('ciudad/<int:pk>/borrar/', views.CiudadDeleteView.as_view(), name='ciudad-borrar'),
    # Grupos
    path('grupos', views.GruposView.as_view(), name='grupos'),
    path('grupo/<int:pk>/', views.GrupoView.as_view(), name='grupo'),
    path('grupo/nuevo/', views.GrupoCreateView.as_view(), name='grupo-nuevo'),
    path('grupo/<int:pk>/editar', views.GrupoUpdateView.as_view(), name='grupo-editar'),
    path('grupo/<int:pk>/borrar/', views.GrupoDeleteView.as_view(), name='grupo-borrar'),
    # Profes
    path('profes', views.ProfesView.as_view(), name='profes'),
    path('profe/<int:pk>/', views.ProfeView.as_view(), name='profe'),
    path('profe/nuevo/', views.ProfeCreateView.as_view(), name='profe-nuevo'),
    path('profe/<int:pk>/editar', views.ProfeUpdateView.as_view(), name='profe-editar'),
    path('profe/<int:pk>/borrar/', views.ProfeDeleteView.as_view(), name='profe-borrar'),
]

studentscrud/models.py
from django.db import models

from django.utils import timezone
from datetime import datetime
from dateutil.relativedelta import relativedelta

from django.core.validators import EmailValidator, BaseValidator
from django.core.exceptions import ValidationError
from django.utils.deconstruct import deconstructible

import studentscrud.utils as utils
from django.conf import settings

@deconstructible
class PastDateValidator():


    def __call__(self, date):
        tz = settings.TIME_ZONE
        now_loc =  utils.to_loc(datetime.now(), tz)
        date_loc = utils.to_loc(date, tz)
        if  now_loc < date_loc:
            raise ValidationError("Indique una fecha en el pasado.")

# Ciudades
class Ciudad(models.Model):

    def __str__(self):
        return self.nombre

    nombre = models.CharField(max_length=200)

# Profesores
class Profesor(models.Model):

    def __str__(self):
        return self.nombre

    nombre = models.CharField(max_length=200)

# Existen grupos que contienen una lista de estudiantes.
# El grupo tiene: nombre, profesor guía.
class Grupo(models.Model):

    def __str__(self):
        return self.nombre

    nombre = models.CharField(max_length=200)
    profesor_guia = models.ForeignKey(Profesor, verbose_name='Profesor guía', on_delete=models.RESTRICT)

# Cada estudiante tiene edad, sexo, nombre, email, 
# fecha de nacimiento , ciudad de nacimiento y grupo.
class Estudiante(models.Model):

    def __str__(self):
        return self.nombre

    def edad(self):
        edad = relativedelta(timezone.now(), self.fecha_nacimiento)
        return edad.years

    nombre = models.CharField(max_length=200)
    email = models.CharField(max_length=200, validators=[EmailValidator()])
    ciudad_nacimiento = models.ForeignKey(Ciudad, verbose_name='Ciudad de nacimiento',  on_delete=models.RESTRICT)
    sexo = models.CharField(max_length=50)
    fecha_nacimiento = models.DateTimeField('Fecha de nacimiento', validators=[PastDateValidator()])
    grupo = models.ForeignKey(Grupo, on_delete=models.RESTRICT)

studentscrud/views.py
from django.shortcuts import render
from django.views import generic

from django.views import generic

from .models import Estudiante

from django.views.generic.edit import FormView

from django.views.generic.edit import CreateView, DeleteView, UpdateView
from django.urls import reverse_lazy

class StudentsView(generic.ListView):
    template_name = 'studentscrud/estudiantes.html'
    context_object_name = 'lista_de_estudiantes'

    def get_queryset(self):
        """Devuelvo todos los estudiantes"""
        return Estudiante.objects.order_by('nombre')

class StudentView(generic.DetailView):
    model = Estudiante
    template_name = 'studentscrud/estudiante.html'

class EstudianteCreateView(CreateView):
    model = Estudiante
    fields = [
        'nombre',
        'sexo',
        'email',
        'fecha_nacimiento',
        'ciudad_nacimiento',
        'grupo'
        ]
    success_url = reverse_lazy('studentscrud:estudiantes')

class EstudianteUpdateView(UpdateView):
    model = Estudiante
    fields = [
        'nombre',
        'sexo',
        'email',
        'fecha_nacimiento',
        'ciudad_nacimiento',
        'grupo'
        ]
    success_url = reverse_lazy('studentscrud:estudiantes')

class EstudianteDeleteView(DeleteView):
    model = Estudiante
    success_url = reverse_lazy('studentscrud:estudiantes')

studentscrud/views/cities.py
from django.shortcuts import render
from django.views import generic

from django.views import generic

from studentscrud.models import Ciudad

from django.views.generic.edit import FormView

from django.views.generic.edit import CreateView, DeleteView, UpdateView
from django.urls import reverse_lazy

class CiudadesView(generic.ListView):
    template_name = 'studentscrud/ciudades.html'
    context_object_name = 'lista_de_ciudades'

    def get_queryset(self):
        """Devuelvo todos las ciudades"""
        return Ciudad.objects.order_by('nombre')

class CiudadView(generic.DetailView):
    model = Ciudad
    template_name = 'studentscrud/ciudad.html'

class CiudadCreateView(CreateView):
    model = Ciudad
    fields = [
        'nombre'
        ]
    success_url = reverse_lazy('studentscrud:ciudades')

class CiudadUpdateView(UpdateView):
    model = Ciudad
    fields = [
        'nombre'
        ]
    success_url = reverse_lazy('studentscrud:ciudades')

class CiudadDeleteView(DeleteView):
    model = Ciudad
    success_url = reverse_lazy('studentscrud:ciudades')

studentscrud/views/groups.py
from django.shortcuts import render
from django.views import generic

from django.views import generic

from studentscrud.models import Grupo

from django.views.generic.edit import FormView

from django.views.generic.edit import CreateView, DeleteView, UpdateView
from django.urls import reverse_lazy

class GruposView(generic.ListView):
    template_name = 'studentscrud/grupos.html'
    context_object_name = 'lista_de_grupos'

    def get_queryset(self):
        """Devuelvo todos las Grupoes"""
        return Grupo.objects.order_by('nombre')

class GrupoView(generic.DetailView):
    model = Grupo
    template_name = 'studentscrud/grupo.html'

class GrupoCreateView(CreateView):
    model = Grupo
    fields = [
        'nombre',
        'profesor_guia'
        ]
    success_url = reverse_lazy('studentscrud:grupos')

class GrupoUpdateView(UpdateView):
    model = Grupo
    fields = [
        'nombre',
        'profesor_guia'
        ]
    success_url = reverse_lazy('studentscrud:grupos')

class GrupoDeleteView(DeleteView):
    model = Grupo
    success_url = reverse_lazy('studentscrud:grupos')

studentscrud/views/profes.py
from django.shortcuts import render
from django.views import generic

from django.views import generic

from studentscrud.models import Profesor as Profe

from django.views.generic.edit import FormView

from django.views.generic.edit import CreateView, DeleteView, UpdateView
from django.urls import reverse_lazy

class ProfesView(generic.ListView):
    template_name = 'studentscrud/profesores.html'
    context_object_name = 'lista_de_profes'

    def get_queryset(self):
        """Devuelvo todos las Profesores"""
        return Profe.objects.order_by('nombre')

class ProfeView(generic.DetailView):
    model = Profe
    template_name = 'studentscrud/profesor.html'

class ProfeCreateView(CreateView):
    model = Profe
    fields = [
        'nombre'
        ]
    success_url = reverse_lazy('studentscrud:profes')

class ProfeUpdateView(UpdateView):
    model = Profe
    fields = [
        'nombre'
        ]
    success_url = reverse_lazy('studentscrud:profes')

class ProfeDeleteView(DeleteView):
    model = Profe
    success_url = reverse_lazy('studentscrud:profes')

studentscrud/views/students.py
from django.shortcuts import render
from django.views import generic

from django.views import generic

from studentscrud.models import Estudiante

from django.views.generic.edit import FormView

from django.views.generic.edit import CreateView, DeleteView, UpdateView
from django.urls import reverse_lazy

class StudentsView(generic.ListView):
    template_name = 'studentscrud/estudiantes.html'
    context_object_name = 'lista_de_estudiantes'

    def get_queryset(self):
        """Devuelvo todos los estudiantes"""
        return Estudiante.objects.order_by('nombre')

class StudentView(generic.DetailView):
    model = Estudiante
    template_name = 'studentscrud/estudiante.html'

class EstudianteCreateView(CreateView):
    model = Estudiante
    fields = [
        'nombre',
        'sexo',
        'email',
        'fecha_nacimiento',
        'ciudad_nacimiento',
        'grupo'
        ]
    success_url = reverse_lazy('studentscrud:estudiantes')

class EstudianteUpdateView(UpdateView):
    model = Estudiante
    fields = [
        'nombre',
        'sexo',
        'email',
        'fecha_nacimiento',
        'ciudad_nacimiento',
        'grupo'
        ]
    success_url = reverse_lazy('studentscrud:estudiantes')

class EstudianteDeleteView(DeleteView):
    model = Estudiante
    success_url = reverse_lazy('studentscrud:estudiantes')

studentscrud/templates/studentscrud/ciudad.html
{% extends "base.html" %}

{% block content %}

<h1>Ciudad</h1>

<div class="container w-lg-50">
    <div class="card">
      <h1>{{ ciudad.nombre }}</h1>
    </div>
</div>

{% endblock content %}

studentscrud/templates/studentscrud/ciudad_confirm_delete.html
{% extends "base.html" %}

{% block content %}

<h1>Ciudad</h1>

<div class="container w-lg-50">
    <form action="" method="post">{% csrf_token %}
        <p>¿Seguro quiere borrar a "{{ object }}"?</p>
        <input type="submit" value="Si" class="btn btn-dark mt-3" />
    </form> 
</div>


{% endblock content %}

studentscrud/templates/studentscrud/ciudad_form.html
{% extends "base.html" %}

{% load crispy_forms_tags %}

{% block content %}

<h1>Ciudad</h1>

<div class="container w-lg-50">
    <form method="post">{% csrf_token %}
        {{ form|crispy }}
        <input type="submit" value="Guardar" class="btn btn-dark mt-3">
    </form>
</div>

{% endblock content %}

studentscrud/templates/studentscrud/ciudades.html
{% extends "base.html" %}

{% block content %}

<h1>Ciudades</h1>

{% if lista_de_ciudades %}

    <table class="table">
        <thead>
          <tr>
            <th scope="col">#</th>
            <th scope="col">Nombre</th>
            <th colspan="2" scope="col"></th>
          </tr>
        </thead>
        <p><a href="{% url 'studentscrud:ciudad-nuevo' %}">Nuevo</a></p>
        <tbody>
          {% for ciudad in lista_de_ciudades %}
          <tr>
            <th scope="row"><a href="{% url 'studentscrud:ciudad' ciudad.id %}">{{ ciudad.id }}</a></th>
            <td>{{ ciudad.nombre }}</td>
            <td><a href="{% url 'studentscrud:ciudad-editar' ciudad.id %}" title="Editar"><i class="bi bi-pencil"></i></a></td>
            <td><a href="{% url 'studentscrud:ciudad-borrar' ciudad.id %}" title="Borrar"><i class="bi bi-trash"></i></a></td>
            
          </tr>
          {% endfor %}
        </tbody>
      </table>

{% else %}
    <p>No hay ciudades</p>
{% endif %}

{% endblock content %}

studentscrud/templates/studentscrud/estudiante.html
{% extends "base.html" %}

{% block content %}

<h1>Estudiante</h1>

<div class="container w-lg-50">
  <div class="card">
      <h1>{{ estudiante.nombre }}</h1>
      <ul class="list-group list-group-flush">
        <li class="list-group-item">Fecha de nacimiento {{ estudiante.fecha_nacimiento|date:"d/m/Y" }}</li>
        <li class="list-group-item">Edad {{ estudiante.edad }}</li>
        <li class="list-group-item">Sexo {{ estudiante.sexo }}</li>
        <li class="list-group-item">Email {{ estudiante.email }}</li>
        <li class="list-group-item">Grupo {{ estudiante.grupo }}</li>
        <li class="list-group-item">Profesor guía {{ estudiante.grupo.profesor_guia }}</li>
      </ul>
    </div>
  </div>

  {% endblock content %}
  

studentscrud/templates/studentscrud/estudiante_confirm_delete.html
{% extends "base.html" %}

{% block content %}

<h1>Estudiante</h1>

<div class="container w-lg-50">
<form action="" method="post">{% csrf_token %}
    <p>¿Seguro quiere borrar a "{{ object }}"?</p>
    <input type="submit" value="Si" class="btn btn-dark mt-3" />
</form>
</div>

{% endblock content %}

studentscrud/templates/studentscrud/estudiante_form.html
{% extends "base.html" %}

{% load crispy_forms_tags %}

{% block content %}

<h1>Estudiante</h1>

<div class="container w-lg-50">
    <form method="post">{% csrf_token %}
        {{ form|crispy }}
        <input type="submit" value="Guardar" class="btn btn-dark mt-3">
    </form>
</div>

{% endblock content %}

studentscrud/templates/studentscrud/estudiantes.html
{% extends "base.html" %}

{% block content %}

<h1>Estudiantes</h1>

{% if lista_de_estudiantes %}

    <table class="table">
        <thead>
          <tr>
            <th scope="col">#</th>
            <th scope="col">Nombre</th>
            <th scope="col">Email</th>
            <th scope="col">Grupo</th>
            <th colspan="2" scope="col"></th>
          </tr>
        </thead>
        <p><a href="{% url 'studentscrud:estudiante-nuevo' %}">Nuevo</a></p>
        <tbody>
          {% for estudiante in lista_de_estudiantes %}
          <tr>
            <th scope="row"><a href="{% url 'studentscrud:estudiante' estudiante.id %}">{{ estudiante.id }}</a></th>
            <td>{{ estudiante.nombre }}</td>
            <td>{{ estudiante.email }}</td>
            <td>
              <a href="{% url 'studentscrud:grupo' estudiante.grupo.id %}">{{ estudiante.grupo }}</a>
            </td>
            <td><a href="{% url 'studentscrud:estudiante-editar' estudiante.id %}" title="Editar"><i class="bi bi-pencil"></i></a></td>
            <td><a href="{% url 'studentscrud:estudiante-borrar' estudiante.id %}" title="Borrar"><i class="bi bi-trash"></i></a></td>
          </tr>
          {% endfor %}
        </tbody>
      </table>

{% else %}
    <p>No hay estudiantes</p>
{% endif %}

{% endblock content %}

studentscrud/templates/studentscrud/grupo_confirm_delete.html
{% extends "base.html" %}

{% block content %}

<h1>Grupo</h1>

<div class="container w-lg-50">
    <form action="" method="post">{% csrf_token %}
        <p>¿Seguro quiere borrar a "{{ object }}"?</p>
        <input type="submit" value="Si" class="btn btn-dark mt-3" />
    </form>
</div>

{% endblock content %}

studentscrud/templates/studentscrud/grupo_form.html
{% extends "base.html" %}

{% load crispy_forms_tags %}

{% block content %}

<h1>Grupo</h1>

<div class="container w-lg-50">
    <form method="post">{% csrf_token %}
        {{ form|crispy }}
        <input type="submit" value="Guardar" class="btn btn-dark mt-3">
    </form>
</div>

{% endblock content %}

studentscrud/templates/studentscrud/grupos.html
{% extends "base.html" %}

{% block content %}

<h1>Grupos</h1>

{% if lista_de_grupos %}

    <table class="table">
        <thead>
          <tr>
            <th scope="col">#</th>
            <th scope="col">Nombre</th>
            <th colspan="2" scope="col"></th>
          </tr>
        </thead>
        <p><a href="{% url 'studentscrud:grupo-nuevo' %}">Nuevo</a></p>
        <tbody>
          {% for grupo in lista_de_grupos %}
          <tr>
            <th scope="row"><a href="{% url 'studentscrud:grupo' grupo.id %}">{{ grupo.id }}</a></th>
            <td>{{ grupo.nombre }}</td>
            <td><a href="{% url 'studentscrud:grupo-editar' grupo.id %}" title="Editar"><i class="bi bi-pencil"></i></a></td>
            <td><a href="{% url 'studentscrud:grupo-borrar' grupo.id %}" title="Borrar"><i class="bi bi-trash"></i></a></td>
          </tr>
          {% endfor %}
        </tbody>
      </table>

{% else %}
    <p>No hay grupoes</p>
{% endif %}

{% endblock content %}

studentscrud/templates/studentscrud/profesor.html
{% extends "base.html" %}

{% block content %}

<h1>Profe</h1>

<div class="container w-lg-50">
  <div class="card">
    <h1>{{ profesor.nombre }}</h1>
  </div>
</div>

{% endblock content %}

studentscrud/templates/studentscrud/profesor_confirm_delete.html
{% extends "base.html" %}

{% block content %}

<h1>Profe</h1>

<div class="container w-lg-50">
    <form action="" method="post">{% csrf_token %}
        <p>¿Seguro quiere borrar a "{{ object }}"?</p>
        <input type="submit" value="Si" class="btn btn-dark mt-3" />
    </form>
</div>

{% endblock content %}

studentscrud/templates/studentscrud/profesores.html
{% extends "base.html" %}

{% block content %}

  <h1>Profes</h1>

  {% if lista_de_profes %}

      <table class="table">
          <thead>
            <tr>
              <th scope="col">#</th>
              <th scope="col">Nombre</th>
              <th colspan="2" scope="col"></th>
            </tr>
          </thead>
          <p><a href="{% url 'studentscrud:profe-nuevo' %}">Nuevo</a></p>
          <tbody>
            {% for profe in lista_de_profes %}
            <tr>
              <th scope="row"><a href="{% url 'studentscrud:profe' profe.id %}">{{ profe.id }}</a></th>
              <td>{{ profe.nombre }}</td>
              <td><a href="{% url 'studentscrud:profe-editar' profe.id %}" title="Editar"><i class="bi bi-pencil"></i></a></td>
              <td><a href="{% url 'studentscrud:profe-borrar' profe.id %}" title="Borrar"><i class="bi bi-trash"></i></a></td>
            </tr>
            {% endfor %}
          </tbody>
        </table>

  {% else %}
      <p>No hay profees</p>
  {% endif %}

{% endblock content %}